<?php foreach ($this->products as $product): ?>
    <article>
        <h3 id="product<?= $product->getId() ?>"><?= $product->getSku() ?></h3>
        <p>
            <a href="<?= $this->url('catalog/product/view', array('id' => $product->getId())) ?>"><?= $product->getName() ?></a>
        </p>

        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <img src="http://alpha-hydro.loc<?=$product->getUploadPath() . $product->getImage()?>" alt="..." class="img-thumbnail">
                </div>
                <div class="col-md-8">
                    <?php if ($productParams[$product->getId()]): ?>
                    <h4>Свойства</h4>
                    <table class="table table-striped table-condensed product-property">
                        <?php foreach ($productParams[$product->getId()] as $param):?>
                            <tr>
                                <td><?= $param['name'] ?></td>
                                <td><?= $param['value'] ?></td>
                            </tr>
                        <?php endforeach;?>
                    </table>
                    <?php endif;?>
                </div>
            </div>
        </div>

        <?php if($productModificationsTable[$product->getId()]):?>
        <h4>Модификации</h4>
        <table class="table table-striped table-condensed product-property">
            <thead>
            <tr>
                <th>Название</th>
                <?php foreach ($productModificationsTable[$product->getId()]['columns'] as $column):?>
                <th><?= $column?></th>
                <?php endforeach;?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($productModificationsTable[$product->getId()]['rows'] as $name => $modification):?>
                <tr>
                    <td><?= $name?></td>
                    <?php foreach ($modification as $value):?>
                        <td><?= $value?></td>
                    <?php endforeach;?>
                </tr>
            <?php endforeach;?>
            </tbody>
        </table>
        <?php endif;?>
    </article>

<?php endforeach; ?>
