<article>
    <h3 id="product<?= $this->product->getId() ?>"><?= $this->product->getName() ?></h3>
    <p>
        <a href="http://alpha-hydro.loc/catalog/<?= $this->product->getFullPath() ?>" target="_blank"><?= $this->product->getFullPath() ?></a>
    </p>

    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="http://alpha-hydro.loc<?=$this->product->getUploadPath() . $this->product->getImage()?>" alt="..." class="img-thumbnail">
            </div>
            <div class="col-md-8">
                <h4>Свойства</h4>
                <table class="table table-striped table-condensed product-property">
                    <?php foreach ($this->productParams as $param):?>
                        <tr>
                            <td><?= $param->getName() ?></td>
                            <td><?= $param->getValue() ?></td>
                        </tr>
                    <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>


    <h4>Модификации</h4>
    <table class="table table-striped table-condensed product-property">
        <thead>
        <tr>
            <td>Название</td>
            <?php foreach ($this->modificationsProperty as $property):?>
                <td><?=$property->getName()?></td>
            <?php endforeach;?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->modificationsTable as $row):?>
            <tr>
                <?php foreach ($row as $value):?>
                    <td><?=$value ?></td>
                <?php endforeach;?>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</article>
